[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "slack_kb_agent"
version = "1.2.0"
dependencies = [
    "sentence-transformers>=2.2.0",
    "faiss-cpu>=1.7.0",
    "numpy>=1.21.0",
    "torch>=1.9.0",
]

[project.scripts]
slack-kb-agent = "slack_kb_agent.cli:main"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["slack_kb_agent"]
