[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "slack_kb_agent"
version = "0.0.1"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["slack_kb_agent"]
