[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "slack_kb_agent"
version = "1.2.0"

[project.scripts]
slack-kb-agent = "slack_kb_agent.cli:main"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["slack_kb_agent"]
