global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@company.com'
  smtp_auth_username: 'alerts@company.com'
  smtp_auth_password: 'your-email-password'

# Templates for alert messages
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts go to PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # Warning alerts go to Slack only
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 1h
    
    # Info alerts go to low-priority channel
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      repeat_interval: 24h

# Inhibition rules (suppress alerts)
inhibit_rules:
  # Suppress warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

# Receivers configuration
receivers:
  - name: 'default-receiver'
    slack_configs:
      - api_url: 'YOUR_DEFAULT_SLACK_WEBHOOK_URL'
        channel: '#general-alerts'
        title: 'Slack KB Agent Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}

  - name: 'critical-alerts'
    # PagerDuty for critical alerts
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: 'Critical alert for Slack KB Agent'
        details:
          summary: '{{ .GroupLabels.alertname }}'
          timestamp: '{{ .CommonAnnotations.timestamp }}'
          
    # Also send to Slack
    slack_configs:
      - api_url: 'YOUR_CRITICAL_SLACK_WEBHOOK_URL'
        channel: '#critical-alerts'
        title: '🚨 CRITICAL: Slack KB Agent'
        color: 'danger'
        text: |
          {{ range .Alerts }}
          *CRITICAL ALERT*
          *Service:* Slack KB Agent
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://localhost:3001/d/slack-kb-agent'
          - type: button
            text: 'View Logs'
            url: 'http://localhost:3001/explore'

  - name: 'warning-alerts'
    slack_configs:
      - api_url: 'YOUR_WARNING_SLACK_WEBHOOK_URL'
        channel: '#monitoring-alerts'
        title: '⚠️ WARNING: Slack KB Agent'
        color: 'warning'
        text: |
          {{ range .Alerts }}
          *Warning Alert*
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'info-alerts'
    slack_configs:
      - api_url: 'YOUR_INFO_SLACK_WEBHOOK_URL'
        channel: '#monitoring-info'
        title: 'ℹ️ INFO: Slack KB Agent'
        color: 'good'
        text: |
          {{ range .Alerts }}
          *Info Alert*
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Email notifications
  - name: 'email-alerts'
    email_configs:
      - to: 'devops@company.com'
        from: 'alerts@company.com'
        subject: 'Slack KB Agent Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>Alert Details</h2>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
          <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
          {{ end }}

  # Microsoft Teams notifications
  - name: 'teams-alerts'
    webhook_configs:
      - url: 'YOUR_TEAMS_WEBHOOK_URL'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alert-user'
            password: 'alert-password'
        title: 'Slack KB Agent Alert'
        text: |
          {{ range .Alerts }}
          **{{ .Annotations.summary }}**
          
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          {{ end }}

# Silence configuration
# Silences can be configured via API or web UI at http://localhost:9093