name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight Checklist
      description: Please confirm these before submitting
      options:
        - label: I have searched for similar issues in the issue tracker
          required: true
        - label: I am using a supported version (see SECURITY.md)
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you running?
      placeholder: "1.7.2"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running the application?
      options:
        - Docker Compose
        - Docker (single container)
        - Local Python installation
        - Kubernetes
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Please provide environment details. You can get some of this by running:
        - `python --version`
        - `docker --version`
        - Operating system and version
      value: |
        - OS: 
        - Python Version: 
        - Docker Version: 
        - Browser (if applicable): 
        - PostgreSQL Version: 
        - Redis Version: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (remove sensitive data)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Please share relevant configuration (remove sensitive data like tokens)
        You can include:
        - Environment variables (without values)
        - Configuration file snippets
        - Docker compose configuration
      render: yaml

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: checkboxes
    id: additional
    attributes:
      label: Additional Context
      description: Is there anything else you can tell us about this issue?
      options:
        - label: This is a security-related issue (consider reporting privately)
        - label: This is blocking my work
        - label: I am willing to submit a PR to fix this issue
        - label: This affects multiple users